<script src="{{ asset('/public/assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('/public/assets/js/popper.min.js') }}"></script>
<script src="{{ asset('/public/assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('/public/assets/js/modernizr.min.js') }}"></script>
<script src="{{ asset('/public/assets/js/detect.js') }}"></script>
<script src="{{ asset('/public/assets/js/fastclick.js') }}"></script>
<script src="{{ asset('/public/assets/js/jquery.blockUI.js') }}"></script>
<script src="{{ asset('/public/assets/js/waves.js') }}"></script>
<script src="{{ asset('/public/assets/js/jquery.nicescroll.js') }}"></script>
<script src="{{ asset('/public/assets/js/Chart.min.js') }}"></script>
<!-- Dropzone js -->
<script src="{{ asset('/public/assets/js/dropzone.min.js') }}"></script>
<script src="{{ asset('/public/assets/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('/public/assets/js/app.js') }}"></script>
<script src="{{ asset('/public/js/app.js') }}"></script>
<script src="{{ asset('/public/assets/custom/custom.js') }}"></script>
